# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-12 15:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('rating', models.IntegerField()),
                ('published', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interactive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('action', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('description', models.CharField(max_length=512)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure_creator.Adventure')),
                ('interactive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adventure_creator.Interactive')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adventure_creator.Item')),
            ],
        ),
        migrations.AddField(
            model_name='interactive',
            name='activator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adventure_creator.Item'),
        ),
    ]
