# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 21:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Interactive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('action', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure_creator.Adventure')),
                ('exit', models.ManyToManyField(to='adventure_creator.Exit')),
                ('interactive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adventure_creator.Interactive')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adventure_creator.Item')),
            ],
        ),
        migrations.AddField(
            model_name='interactive',
            name='activator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adventure_creator.Item'),
        ),
    ]
