# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure_creator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='interactive',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure_creator.Action'),
        ),
    ]
