# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-12 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure_creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactive',
            name='reward',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewarded_item', to='adventure_creator.Item'),
        ),
        migrations.AlterField(
            model_name='interactive',
            name='activator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activator_item', to='adventure_creator.Item'),
        ),
    ]
