# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-12 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure_creator', '0002_auto_20170312_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactive',
            name='reward',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewarded_item', to='adventure_creator.Item'),
        ),
        migrations.AlterField(
            model_name='room',
            name='interactive',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adventure_creator.Interactive'),
        ),
        migrations.AlterField(
            model_name='room',
            name='item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adventure_creator.Item'),
        ),
    ]
