# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure_creator', '0002_auto_20170225_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactive',
            name='action',
            field=models.CharField(max_length=32),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
    ]
